"""Clarification question model for project intake."""

from datetime import datetime
from enum import StrEnum

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class QuestionType(StrEnum):
    """Types of clarification questions."""

    TEXT = "text"  # Free-form text response
    SINGLE_SELECT = "single_select"  # Choose one option
    MULTI_SELECT = "multi_select"  # Choose multiple options
    DATE_RANGE = "date_range"  # Start and end date
    NUMBER = "number"  # Numeric value
    BOOLEAN = "boolean"  # Yes/No


class QuestionCategory(StrEnum):
    """Categories of clarification questions."""

    SCOPE = "scope"  # About research scope
    METHODOLOGY = "methodology"  # About research methods
    SOURCES = "sources"  # About data sources
    CONSTRAINTS = "constraints"  # About limitations/constraints
    OUTPUT = "output"  # About expected outputs
    OTHER = "other"


class ClarificationQuestion(Base):
    """
    Clarification question for refining project scope.

    These questions are generated by the AI to help clarify
    the research objective and define the scope.
    """

    __tablename__ = "clarification_questions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Link to project
    project_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Question details
    question: Mapped[str] = mapped_column(Text, nullable=False)
    question_type: Mapped[QuestionType] = mapped_column(
        String(50),
        default=QuestionType.TEXT,
        nullable=False,
    )
    category: Mapped[QuestionCategory] = mapped_column(
        String(50),
        default=QuestionCategory.SCOPE,
        nullable=False,
    )

    # For select questions, store the options
    options: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    # Options structure:
    # [
    #     {"value": "option1", "label": "Option 1"},
    #     {"value": "option2", "label": "Option 2"}
    # ]

    # Help text to explain the question
    help_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Which scope field this question maps to (if any)
    scope_field: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Answer
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    answer_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # For structured answers (multi-select, date ranges, etc.)

    # Is this question required?
    is_required: Mapped[bool] = mapped_column(Boolean, default=True)

    # Order in the question sequence
    order: Mapped[int] = mapped_column(Integer, default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    answered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Relationship
    project = relationship("Project", back_populates="clarification_questions")

    def __repr__(self) -> str:
        return f"<ClarificationQuestion(id={self.id}, project_id={self.project_id}, answered={self.is_answered})>"

    @property
    def is_answered(self) -> bool:
        """Check if the question has been answered."""
        if not self.is_required:
            return True
        return self.answer is not None or self.answer_data is not None
