"""Pydantic schemas for request/response validation."""

from app.schemas.clarification import (
    AnswerQuestionRequest,
    ClarificationQuestionResponse,
    ClarificationQuestionsListResponse,
    ClarificationStatusResponse,
    GenerateQuestionsRequest,
    QuestionCategory,
    QuestionOption,
    QuestionType,
)
from app.schemas.health import HealthResponse, HealthStatus
from app.schemas.project import (
    ProjectCreateRequest,
    ProjectDetail,
    ProjectListResponse,
    ProjectScope,
    ProjectScopeUpdateRequest,
    ProjectStatus,
    ProjectStatusUpdateRequest,
    ProjectSummary,
    ProjectUpdateRequest,
)
from app.schemas.provider import (
    ChatMessageRequest,
    ChatRequest,
    ChatResponseSchema,
    EmbeddingRequest,
    EmbeddingResponseSchema,
    ModelListResponse,
    ProviderCapabilitiesResponse,
    ProviderHealthResponse,
    ProviderInfo,
    ProviderListResponse,
)
from app.schemas.document import (
    AddPaperRequest,
    BulkAddPapersRequest,
    BulkAddPapersResponse,
    DocumentChunkResponse,
    DocumentCreate,
    DocumentListResponse,
    DocumentResponse,
    DocumentStatus,
    DocumentSummary,
    DocumentUpdate,
    ProcessingRequest,
    ProcessingStatus,
    SemanticSearchRequest,
    SemanticSearchResponse,
    SimilarChunkResult,
)
from app.schemas.job import (
    BatchProcessRequest,
    BatchProcessResponse,
    JobCreate,
    JobDetail,
    JobListResponse,
    JobPriority,
    JobProgress,
    JobStatsResponse,
    JobStatus,
    JobSummary,
    JobType,
    ResearchJobConfig,
    StartResearchJobRequest,
    StartResearchJobResponse,
)
from app.schemas.job_progress import (
    CheckpointState,
    JobProgressSummary,
    LogEntryType,
    ProgressLogCreate,
    ProgressLogEntry,
    ProgressLogList,
    ResumeJobRequest,
)

__all__ = [
    # Health
    "HealthResponse",
    "HealthStatus",
    # Provider
    "ProviderCapabilitiesResponse",
    "ProviderInfo",
    "ProviderListResponse",
    "ProviderHealthResponse",
    "ModelListResponse",
    "ChatMessageRequest",
    "ChatRequest",
    "ChatResponseSchema",
    "EmbeddingRequest",
    "EmbeddingResponseSchema",
    # Project
    "ProjectStatus",
    "ProjectScope",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectScopeUpdateRequest",
    "ProjectStatusUpdateRequest",
    "ProjectSummary",
    "ProjectDetail",
    "ProjectListResponse",
    # Clarification
    "QuestionType",
    "QuestionCategory",
    "QuestionOption",
    "AnswerQuestionRequest",
    "GenerateQuestionsRequest",
    "ClarificationQuestionResponse",
    "ClarificationQuestionsListResponse",
    "ClarificationStatusResponse",
    # Document
    "DocumentStatus",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentSummary",
    "DocumentListResponse",
    "DocumentChunkResponse",
    "AddPaperRequest",
    "BulkAddPapersRequest",
    "BulkAddPapersResponse",
    "ProcessingRequest",
    "ProcessingStatus",
    "SemanticSearchRequest",
    "SemanticSearchResponse",
    "SimilarChunkResult",
    # Job
    "JobType",
    "JobStatus",
    "JobPriority",
    "JobCreate",
    "JobProgress",
    "JobSummary",
    "JobDetail",
    "JobListResponse",
    "JobStatsResponse",
    "ResearchJobConfig",
    "StartResearchJobRequest",
    "StartResearchJobResponse",
    "BatchProcessRequest",
    "BatchProcessResponse",
    # Job Progress
    "LogEntryType",
    "ProgressLogEntry",
    "ProgressLogCreate",
    "CheckpointState",
    "ProgressLogList",
    "JobProgressSummary",
    "ResumeJobRequest",
]
